name: comic-downloader
services:
  comic-downloader:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: comic-downloader
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - BROWSERLESS_HOST_IP=${BROWSERLESS_HOST_IP:?error}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN:?error}
      - DOCKER=${DOCKER:?error}
      - DEBUG=${DEBUG}
    volumes:
      - ./downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
