name: comic-downloader
services:
  comic-downloader:
    image: NorkzYT/comic-downloader:1.0.0
    container_name: comic-downloader
    pull_policy: always
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /opt/appdata/comic-downloader/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
