# Installation: https://www.browserless.io/docs/docker-quickstart
name: comic-downloader-browserless
services:
  comic-downloader-browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: comic-downloader-browserless
    pull_policy: always
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CONCURRENT=2
      - TIMEOUT=300000
      - QUEUED=10
      - HEALTH=true
      - MAX_MEMORY_PERCENT=90
      - MAX_CPU_PERCENT=80
      - ALLOW_GET=true
      - ALLOW_FILE_PROTOCOL=true
      - METRICS_JSON_PATH=/root/metrics.json
      - DATA_DIR=/tmp/my-profile
      - DOWNLOAD_DIR=/downloads
      # Proxy:
      # - EXTERNAL=${protocol}://${username}:${password}@${host}:${port} 
    ports:
      - 8454:3000
    volumes:
      - /opt/appdata/comic-downloader-browserless/root:/root
      - /opt/appdata/comic-downloader-browserless/tmp/my-profile:/tmp/my-profile
      - /opt/appdata/comic-downloader-browserless/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
