# Installation: https://www.browserless.io/docs/docker-quickstart
name: comic-downloader-browserless
services:
  comic-downloader-browserless-dev:
    image: ghcr.io/browserless/chromium:latest
    container_name: comic-downloader-browserless-dev
    pull_policy: always
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - TIMEOUT=300000
      - HEALTH=true
      - ALLOW_GET=true
      - ALLOW_FILE_PROTOCOL=true
      - METRICS_JSON_PATH=/root/metrics.json
      - DATA_DIR=/tmp/my-profile
      - DOWNLOAD_DIR=/downloads
      # Proxy:
      # - EXTERNAL=${protocol}://${username}:${password}@${host}:${port} 
    ports:
      - 8455:3000
    volumes:
      - ./volume/root:/root
      - ./volume/tmp/my-profile:/tmp/my-profile
      - ./volume/downloads:/downloads
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
