name: 🚀 Release

on:
  release:
    types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel:
        # linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - name: Get short version and tag
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "tag=$(git describe --tags)" >> $GITHUB_ENV
      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.23.0"
          project_path: "."
          binary_name: "comic-downloader"
          extra_files: LICENSE README.md
          ldflags: >-
            -X 'github.com/NorkzYT/comic-downloader/cmd.Version=${{ env.sha_short }}'
            -X 'github.com/NorkzYT/comic-downloader/cmd.Tag=${{ env.tag }}'
